--- 
- name: CONFIGURE OSPF ADDRESSING 
  hosts: hosts
  gather_facts: false 
  connection: local 
 
  tasks: 
   - name: OSPF SETUP
     ios_config:
        parents: "router ospf 1"
        lines:
            - network 192.168.0.0 0.0.0.255 area 0

   - name: SET OSPF authentication  
     ios_config: 
       parents: "interface GigabitEthernet1" 
       lines: 
         - description OSPF interface
         - ip ospf authentication-key cisco

   - name: SHOW IPv4 INTERFACE SHOW RUN  
     ios_command: 
       commands: 
         - show run | section interface

     register: output 
 
   - name: SAVE OUTPUT ./ios_configurations/ 
     copy:  
       content: "{{ output.stdout[0] }}" 
       dest: "ios_configurations/Interface_configuration_{{ inventory_hostname }}.txt" 
   - name: SHOW RUN OSPF  
     ios_command: 
       commands: 
         - show run | section router ospf

     register: output 
 
   - name: SAVE OUTPUT ./ios_configurations/ 
     copy:  
       content: "{{ output.stdout[0] }}" 
       dest: "ios_configurations/OSPF_{{ inventory_hostname }}.txt" 
